# PREPOCESSING DATA

## 19 Februari 2019
### Data Cleaning (Missing value & Outlier)

In [1]:
import pandas as pd
import numpy as np

In [2]:
movie = pd.read_csv("D:\DATA MINING\movie_metadata.csv",sep=";")
movie.head().append(movie.tail())

,movie_code,duration,facenumber_in_poster,country,budget,gross,num_voted_users,num_user_for_reviews,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,imdb_score,imdb_score_class
0,1,178.0,0.0,USA,237000000.0,760505847.0,886204,3054.0,723.0,33000,0.0,1000.0,936.0,855.0,4834,7.9,Good
1,2,169.0,0.0,USA,300000000.0,309404152.0,471220,1238.0,302.0,0,563.0,40000.0,5000.0,1000.0,48350,7.1,Good
2,3,148.0,1.0,UK,245000000.0,200074175.0,275868,994.0,602.0,85000,0.0,11000.0,393.0,161.0,11700,6.8,Good
3,4,164.0,0.0,USA,250000000.0,448130642.0,1144337,2701.0,813.0,164000,22000.0,27000.0,23000.0,23000.0,106759,8.5,Excellent
4,5,132.0,1.0,USA,263700000.0,73058679.0,212204,738.0,462.0,24000,475.0,640.0,632.0,530.0,1873,6.6,Good
5037,5038,87.0,2.0,Canada,NaN,NaN,629,6.0,1.0,84,2.0,637.0,470.0,318.0,2283,7.7,Good
5038,5039,43.0,1.0,USA,NaN,NaN,73839,359.0,43.0,32000,NaN,841.0,593.0,319.0,1753,7.5,Good
5039,5040,76.0,0.0,USA,1400.0,NaN,38,3.0,13.0,16,0.0,0.0,0.0,0.0,0,6.3,Good
5040,5041,100.0,5.0,USA,NaN,10443.0,1255,9.0,14.0,660,0.0,946.0,719.0,489.0,2386,6.3,Good
5041,5042,90.0,0.0,USA,1100.0,85222.0,4285,84.0,43.0,456,16.0,86.0,23.0,16.0,163,6.6,Good

In [3]:
movie.describe() #statistika deskriptif

,movie_code,duration,facenumber_in_poster,budget,gross,num_voted_users,num_user_for_reviews,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,imdb_score
count,5042.000000,5028.000000,5029.000000,4.551000e+03,4.159000e+03,5.042000e+03,5022.000000,4993.000000,5042.000000,4938.000000,5035.000000,5029.000000,5020.000000,5042.000000,5042.000000
mean,2521.500000,107.201074,1.371446,3.975262e+07,4.846841e+07,8.368475e+04,272.770808,140.194272,7527.457160,686.621709,6561.323932,1652.080533,645.009761,9700.959143,6.442007
std,1455.644359,25.197441,2.013683,2.061149e+08,6.845299e+07,1.384940e+05,377.982886,121.601675,19322.070537,2813.602405,15021.977635,4042.774685,1665.041728,18165.101925,1.125189
min,1.000000,7.000000,0.000000,2.180000e+02,1.620000e+02,5.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.600000
25%,1261.250000,93.000000,0.000000,6.000000e+06,5.340988e+06,8.599250e+03,65.000000,50.000000,0.000000,7.000000,614.500000,281.000000,133.000000,1411.250000,5.800000
50%,2521.500000,103.000000,1.000000,2.000000e+07,2.551750e+07,3.437100e+04,156.000000,110.000000,166.000000,49.000000,988.000000,595.000000,371.500000,3091.000000,6.600000
75%,3781.750000,118.000000,2.000000,4.500000e+07,6.230944e+07,9.634700e+04,326.000000,195.000000,3000.000000,194.750000,11000.000000,918.000000,636.000000,13758.750000,7.200000
max,5042.000000,511.000000,43.000000,1.221550e+10,7.605058e+08,1.689764e+06,5060.000000,813.000000,349000.000000,23000.000000,640000.000000,137000.000000,23000.000000,656730.000000,9.500000

In [4]:
np.sum(movie.isnull()) #missing value

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                       491
gross                        883
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

### missing value <10% setiap variabel diabaikan/imputasi
### missing value >15% setiap variabel dan tidak berkorelasi dg yang lain dihapus jika berkorelasi diimputasi
### missing value >50% setiap variabel dihapus variabelnya
### imputasi = mengisi missing value
#### mean (kontinu), modus (kategorik)

In [5]:
#imputasi with mean
movie['duration'] = movie['duration'].fillna(107.201074)
movie['facenumber_in_poster'] = movie['facenumber_in_poster'].fillna(1.371446)
movie['budget'] = movie['budget'].fillna(3.975262e+07)
movie['gross'] = movie['gross'].fillna(4.846841e+07)
movie['num_user_for_reviews'] = movie['num_user_for_reviews'].fillna(272.770808)
movie['num_critic_for_reviews'] = movie['num_critic_for_reviews'].fillna(140.194272)
movie['director_facebook_likes'] = movie['director_facebook_likes'].fillna(686.621709)
movie['actor_1_facebook_likes'] = movie['actor_1_facebook_likes'].fillna(movie['actor_1_facebook_likes'].mean())
movie['actor_2_facebook_likes'] = movie['actor_2_facebook_likes'].fillna(movie['actor_2_facebook_likes'].mean())
movie['actor_3_facebook_likes'] = movie['actor_3_facebook_likes'].fillna(movie['actor_3_facebook_likes'].mean())
np.sum(movie.isnull())

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      4
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

In [6]:
[movie['country'].mode()]

[0    USA
 dtype: object]

In [7]:
#imputasi with mode 
from scipy.stats import mode

movie['country']=movie['country'].fillna(movie['country']).dropna().mode()[0]
np.sum(movie.isnull())

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      0
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

### Outlier

In [8]:
#mengatasi outlier 
from scipy import stats

movie1=movie.drop('country',1)
z = np.abs(stats.zscore(movie1._get_numeric_data()))
print(z)
movie=movie[(z<3).all(axis=1)]
print(movie.shape)

[[1.73170732 2.81395543 0.68201074 ... 0.12640574 0.26795566 1.29590414]
 [1.73102027 2.4562438  0.68201074 ... 0.21368996 2.12786442 0.58484214]
 [1.73033322 1.62158335 0.18471742 ... 0.29135456 0.11005934 0.3181939 ]
 ...
 [1.73033322 1.24010965 0.68201074 ... 0.38827014 0.53409672 0.12621985]
 [1.73102027 0.28621199 1.80445584 ... 0.09391165 0.40273293 0.12621985]
 [1.73170732 0.68366935 0.68201074 ... 0.37863877 0.52512258 0.1404284 ]]
(4258, 17)

In [9]:
movie.head()

,movie_code,duration,facenumber_in_poster,country,budget,gross,num_voted_users,num_user_for_reviews,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,imdb_score,imdb_score_class
4,5,132.0,1.0,USA,263700000.0,73058679.0,212204,738.0,462.0,24000,475.0,640.0,632.0,530.0,1873,6.6,Good
6,7,100.0,1.0,USA,260000000.0,200807262.0,294810,387.0,324.0,29000,15.0,799.0,553.0,284.0,2036,7.8,Good
11,12,106.0,1.0,USA,200000000.0,168368427.0,330784,1243.0,403.0,0,395.0,451.0,412.0,393.0,2023,6.7,Good
13,14,150.0,1.0,USA,215000000.0,89289910.0,181792,711.0,450.0,48000,563.0,40000.0,2000.0,1000.0,45757,6.5,Good
15,16,150.0,4.0,USA,225000000.0,141614023.0,149922,438.0,258.0,0,80.0,22000.0,216.0,201.0,22697,6.6,Good